mysociety/pombola

pombola/core/templates/core/person_base.html

ZA: consistent sidebar styling for person appearances page

---

pombola/core/models.py
pombola/core/tests/test_views.py
pombola/core/views.py
pombola/images/models.py
pombola/south_africa/tests.py

This series of commits make various changes to reduce the huge number
of queries that some pages on Pombola cause.

Some changes to reduce the number of queries Pombola makes

---

pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/south_africa/question_index.html
pombola/south_africa/templates/south_africa/question_section_detail.html
pombola/south_africa/templates/south_africa/question_speech.html
pombola/south_africa/views.py

Implements the first stages of #1492. This is largely intended to enable work on the design of the new landing page and further work to ```views.py``` is probably necessary.

ZA: New question and answer landing page

---

pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/south_africa/question_index.html
pombola/south_africa/views.py

Part of https://github.com/mysociety/pombola/issues/1492

ZA: Question page improvements

---

pombola/kenya/static/js/survey.js
pombola/kenya/static/sass/_kenya_header.scss
pombola/kenya/templates/base.html
pombola/kenya/templates/header.html
pombola/settings/kenya_base.py
pombola/templates/default_base.html

* Solves https://github.com/mysociety/research/issues/50

Add link asking Mzalendo users to complete research survey

---

pombola/south_africa/templates/core/person_detail.html

Add the address details to the profile page sidebar if it's been set
Closes #1604

ZA: Show the address on person profile pages

---

pombola/hansard/management/commands/hansard_check_for_new_sources.py

The web scraper in the `hansard_check_for_new_sources` management
command has not been finding new Hansard PDF files since the Kenyan
Parliament site was relaunched over the Christmas 2014 break. This
update adjusts the existing scraper for the new URLs and HTML layout.
As the National Assembly listings page now only links to the last 15
documents, code has been added to traverse across multiple pages if the
final document on the current page is treated as a new source. The hope
is that this should be reached very infrequently after the initial
catchup scraper run.
Resolves #1634

KE: Update Hansard scraper to use new site structure

---

pombola/kenya/static/js/click-tracking.js
pombola/kenya/static/sass/_county_performance.scss
pombola/kenya/templates/youth-employment.html
pombola/kenya/urls.py
pombola/kenya/views.py

WIP - fix the outstanding issues for the Youth Employment Bill page

---

pombola/kenya/templates/youth-employment.html

thanks to @davewhiteland for the video editing skills :smile_cat: 
Closes #1690

Link to the combined YouTube video

---

pombola/info/migrations/0012_auto__add_viewcount__add_unique_viewcount_date_page.py
pombola/info/models.py
pombola/info/tests.py
pombola/info/views.py
pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/info/_blog_sidebar.html

Store counts of views of blog posts. Use these to display a list of popular posts in the sidebar.
Fixes #1671

1671 za popular blog posts

---

pombola/kenya/templates/youth-employment.html
pombola/kenya/urls.py
pombola/kenya/views.py

As requested by MIT / Mzalendo.

Add a new youth employment experiment bill: generic version only

---

pombola/core/popolo.py
pombola/core/tests/test_popolo.py

Some positions (e.g. those representing an MP for a particular
constituency) have a place attribute. This wasn't being exported
in the nightly JSON export, however. This commit introduces a change
so that the place data is exported as the 'area' attribute of a
Popolo membership.  In addition, if the place is specific to a
particular parliamentary session (as happens with constituencies in
Mzalendo) the parliamentary session data is included under the
'session' attribute of the area.
Fixes #1688

Include place data for positions in the Popolo JSON output

---

pombola/search/tests/views.py
pombola/search/views.py

The code for this had clearly never been working at all - just needed a quick tweak to get it going.
Fixes #1766.

Fix hansard search traceback, and add a basic test.

---

pombola/south_africa/management/commands/south_africa_update_constituency_office_address.py
pombola/south_africa/management/helpers.py

We could update addresses using the
south_africa_update_constituency_offices script, but that's a complex
script that requires JSON data for all the constituency offices - if we
only need to update the address of a couple of constituency offices
then this script is a safer option.

Add a script for updating the street address of a constituency office

---

pombola/core/views.py
pombola/south_africa/templates/home.html

Update sort order for position views and fix MP profiles link

---

pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/core/person_detail.html

Mostly @duncanparkes’ fine work.
Fixes #1825.

ZA attendance small fixes

---

pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/core/organisation_people.html
pombola/south_africa/tests.py
pombola/south_africa/urls.py
pombola/south_africa/views.py

Don't merge this until @zarino has had a look for style.
Add an A-Z of links to limit people by the first letter of their name.
Fixes #1518.

1518 A-Z links on organisation people lists

---

pombola/south_africa/templates/footer.html
pombola/south_africa/templates/menu_entries.html

These are the code changes required for a whole collection of issues #1850, #1851, #1852, #1853, #1854.
Most of this is very routine, the one thing I wonder whether we should be doing is the changes to the footer, where it's no longer in sync with the menus.

1852 za extras menu

---

pombola/south_africa/templates/core/person_detail.html
pombola/south_africa/tests.py
pombola/south_africa/views.py

ZA: Fix duplicate organisations from important positions

---

pombola/nigeria/templates/site_header_search.html

Changing search suggestions

---

pombola/settings/south_africa_base.py
pombola/south_africa/static/css/libs/datatables-1.10.10.css
pombola/south_africa/static/js/attendance-table.js
pombola/south_africa/static/js/libs/datatables-1.10.10.js
pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/home.html
pombola/south_africa/templates/south_africa/mp_attendance.html
pombola/south_africa/urls.py
pombola/south_africa/views.py

This branch implements a page to show MP attendance data obtained from api.pmg.org.za.
Data is retrieved from the API, manipulated in the view and presented in a table on it own page. There is a link to this page from the home page. (Retrieving data by year is currently not supported by the API at the moment.)
The Datatables jQuery library is used to make the table sortable by columns, and for client side search.
The external assets for this is only loaded on the MP attendance page.

Mp attendance page

---

pombola/kenya/management/commands/kenya_hansard_speech_statistics.py

Instead of just including people who speak, include all members of NA
and Senators.

For the Kenya hansard stats, include all politicians.

---

pombola/south_africa/templates/south_africa/mp_attendance.html

This merely adds a note on the methodology of calculating attendance.

Display note on methodology of MP attendance

---

pombola/images/migrations/0002_increase_image_path_length.py
pombola/images/models.py
pombola/south_africa/management/commands/south_africa_import_new_constituency_office_locations.py
pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/core/organisation_detail.html

PMG are conducting an exercise to go to all the constituency offices
and get accurate locations for them and photographs. The data they
collect is available as a CSV, and this new management command
processes that CSV and updates our data with the improved locations.
Fixes part of #1938.

Add a script to import new constituency office locations.

---

pombola/core/templates/core/person_base.html
pombola/core/templatetags/absolute_url.py
pombola/templates/default_base.html

Open Graph for people pages

---

pombola/south_africa/static/sass/_south-africa_overrides.scss

Thanks @zarino for the solution.
Fixes #1843.

[ZA] Fix search button alignment.

---

pombola/south_africa/templates/core/person_detail.html

[ZA] Fix pluralization of "meetings" on appearances tab

---

pombola/kenya/urls.py
pombola/kenya/views.py

1991 missing constituency

---

pombola/search/templates/search/global_search.html

Search: Don't say there are 0 results if there are Top Hits

---

pombola/core/models.py
pombola/core/templates/core/person_experience.html
pombola/kenya/templates/core/person_experience.html

Fixes #1964 (paired with @chrismytton)

1964 future previous positions

---

pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/south_africa/organisation_house.html
pombola/south_africa/tests.py
pombola/south_africa/views.py

Fixes #1829 (paired with @chrismytton)

[ZA] Add seat counts as well as percentages and reorder.

---

pombola/core/management/commands/core_merge_organisations.py
pombola/core/management/commands/core_merge_people.py
pombola/core/management/merge.py
pombola/core/tests/test_commands.py

Nearly ready - just needs slugredirect checking on the views.
Closes #2020

2020 organisation merge command

---

pombola/core/admin.py

Order positions in the inline admin on people and organisations.

---

pombola/admin_additions/templates/admin/base_site.html

Add google analytics to the admin.

---

pombola/south_africa/static/js/rep-locator.js
pombola/south_africa/static/js/tabs.js

We don't have any data about how many people try changing tab on the
person pages or rep locator pages; this event tracking code should
record that data.

Track clicks on jQuery tabs in Google Analytics

---

pombola/south_africa/templates/footer.html
pombola/south_africa/templates/site_header_logo.html

Changing where the newsletter icon goes to on the header and footer for People's Assembly. Closes #2176

2176 change newsletter link za

---

pombola_sayit/management/commands/pombola_sayit_sync_pombola_to_popolo.py
pombola_sayit/tests.py

We need to add all the possible Pombola Person slugs as Identifier
objects on the SayIt Speaker so that we can use them in name resolution
when processing data from the Code4SA / PMG API for questions and
answers.

pombola_sayit: also create Identifier objects with Pombola slugs

---

pombola/core/templatetags/clean_html.py
pombola/core/tests/test_clean_html_templatetags.py
pombola/south_africa/templates/south_africa/question_index.html
pombola/south_africa/views.py
requirements.txt

Most of this has been done in `za-hansard` already - this is just
updating Pombola to use that work, and fixing some presentational
issues.

Switch to incorporating questions & answers from the PMG API

---

pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/core/person_detail.html
pombola/south_africa/templates/core/person_speech_list.html
pombola/south_africa/templates/south_africa/person_attendances.html
pombola/south_africa/tests.py
pombola/south_africa/urls.py
pombola/south_africa/views/attendance.py
pombola/south_africa/views/person.py

This adds a page for listing all meetings attended by a person, in a similar way as is done with appearances.
Some small changes to the styles have been made for the pages that display the appearances and attendances, making the items and their elements more readable.

2276 view all attendance records

---

pombola/south_africa/urls.py

[ZA] Add redirect for /attendance to /mp-attendance

---

pombola/south_africa/static/js/mp-profiles-live-filter.js

[ZA] Add tracking of usage of MP search box

---

pombola/south_africa/templates/menu_entries.html

[ZA] Rearrange menu template to match new order of menu items

---

pombola/core/static/js/functions.js
pombola/kenya/static/sass/_kenya_home.scss
pombola/kenya/templates/home.html

Fixes #2303.
Also fixes an old bug, where pressing either the Next or Previous person buttons would make the "Featured Person" heading disappear. Been meaning to get rid of that for a _long_ time!

[KE] Move Featured Person slider to top of homepage

---

pombola/kenya/templates/home.html

changing wording on Dokeza button as per Jessica's instructions

Update Dokeza wording

---

pombola/south_africa/templates/core/person_detail.html

Add a span around email addresses to make scraping for EP easier

---

pombola/south_africa/templates/core/person_detail.html
pombola/south_africa/templates/home.html

A couple of small wording tweaks to People's Assembly following the launch of Write in Public functionality

Za feedback tweaks feb 2018

---

pombola/south_africa/static/sass/_south-africa_overrides.scss

This is as large as they can sensibly get

Za make home buttons bigger

---

pombola/south_africa/templates/home.html

As requested by PMG change the survey link on the homepage.

[ZA] Change homepage survey link

---

pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/core/organisation_detail.html
pombola/south_africa/templates/home.html
pombola/south_africa/templates/writeinpublic/committee-messages.html
pombola/south_africa/urls.py
pombola/writeinpublic/forms.py
pombola/writeinpublic/templates/writeinpublic/committee-write-draft.html
pombola/writeinpublic/templates/writeinpublic/committee-write-preview.html
pombola/writeinpublic/templates/writeinpublic/committee-write-recipients.html
pombola/writeinpublic/templates/writeinpublic/message.html
pombola/writeinpublic/tests.py
pombola/writeinpublic/views.py

This adds the ability to write to a committee alongside the existing Write to an MP functionality.
Fixes #1682

[ZA] Write to a committee

---

pombola/core/admin.py
pombola/core/fixtures/test_data.json
pombola/core/migrations/0007_add_preferred_contact_option.py
pombola/core/models.py
pombola/core/tests/test_commands.py
pombola/core/tests/test_models.py
pombola/core/tests/test_popolo.py
pombola/south_africa/templates/core/person_detail.html
pombola/south_africa/tests.py
pombola/south_africa/views/person.py
pombola/writeinpublic/tests.py

[WIP] [ZA] Allow email addresses to be marked as preferred.

---

pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/home.html

An attempt at fixing #2415, by making it more obvious that you should enter a location into the search box, not an MP’s name.

[ZA] Tweak presentation of homepage “Find your rep” form

---

pombola/south_africa/tests.py
pombola/south_africa/views/attendance.py

Check for an empty party list, as some ministers don't have parties associated with them.

Check for empty party list

---

pombola/kenya/templates/header.html
pombola/settings/base.py

This may well need some design time for extra pop!
* Closes #2446

[KE] Add a survey link to Mzalendo

---

pombola/south_africa/templates/interests_register/index.html
pombola/south_africa/templates/interests_register/index_complete.html
pombola/south_africa/templates/interests_register/index_numberbyrepresentative.html
pombola/south_africa/templates/interests_register/index_section.html
pombola/south_africa/templates/interests_register/source.html
pombola/south_africa/tests.py
pombola/south_africa/views/interests.py

@mhl 
These are changes that have been requested to improve the member's interests page.

2445 improve members interests page

---

pombola/south_africa/data/members-interests/2017.json
pombola/south_africa/data/members-interests/2017_for_import.json

@mhl
The source that was imported incorrectly points to the 2016 register. This update fixes it in the raw data.

Fix member's interests 2017 source

---

pombola/south_africa/templates/menu_entries.html

[ZA] Remove blog submenu from main nav

---

pombola/south_africa/static/sass/_south-africa_overrides.scss
pombola/south_africa/templates/core/generic_list_item.html
pombola/south_africa/templates/core/parliament_list_item.html

[ZA] Custom design for "list of parliaments" page

---

BACKGROUND.md

The intention of this file is quite a high level "So, you've been asked
to maintain Pombola?" description of things that would be important or
helpful to know.

Document background information that might be useful

---

pombola/hansard/management/commands/hansard_check_for_new_sources.py

The official site that we scrape the Hansard PDFs from has had a redesign, which means the selectors used to find the PDFs need to be updated to handle it.
Part of https://github.com/mysociety/pombola/issues/2502
This change means the `hansard_check_for_new_sources` script now runs to completion (when I run it locally, at least). However when I tried to run the full `bin/update_hansard.bash` script it fails because some older PDFs are 404ing. I don't think this is a problem, because on the live site we've parsed everything up to August 2018, but either way I think the easier thing to do it just put this live and see if we get any fresh errors.

[KE] Update Hansard scraper to handle new site

---

pombola/kenya/static/sass/_kenya_home.scss
pombola/kenya/static/sass/_shujaaz.scss
pombola/kenya/templates/_person_gallery_item.html
pombola/kenya/templates/home.html
pombola/kenya/templates/shujaaz-2018.html

2018 Shujaaz voting has now closed, and winners ("finalists") have been chosen. Update the homepage and /shujaaz/2018 page to reflect this.

2018 Shujaaz Nominees -> Finalists

---

pombola/hansard/models/entry.py
pombola/kenya/templates/core/person_appearances.html
pombola/kenya/views.py

[KE] Group speech counts for MPs by year instead of month.

---

pombola/south_africa/templates/menu_entries.html

Make it clearer that this is the page to visit if you want to write to a committee.
Fixes #2557

[ZA] Change committee navigation text

---

pombola/hansard/models/entry.py

More fixes to help with matching constituency and party names.
Part of https://github.com/mysociety/pombola/issues/2473

[KE] Hansard name matching fixes

---

pombola/south_africa/data/elections/2019/committee-emails.csv
pombola/south_africa/management/commands/south_africa_import_email_addresses_elections_2019.py

These are the new emails post-elections 2019.
Part of https://github.com/mysociety/pombola/issues/2593

[ZA] Add command to import new committee emails

---

pombola/core/models.py
pombola/south_africa/urls.py
pombola/south_africa/views/api.py

Adds a Popolo JSON API for National Assembly members.
Part of https://github.com/mysociety/pombola/issues/2651

National Assembly Popolo API

---

pombola/writeinpublic/views.py

This updates the WriteInPublic views to use pombola IDs, rather than EveryPolitician UUIDs. This matches the changes we've made in the writeinpublic repo.
Part of #2651

Update WriteInPublic integration

---

bin/update_za_hansard.bash
pombola/za_hansard/management/commands/za_hansard_check_for_new_sources.py
pombola/za_hansard/management/commands/za_hansard_check_for_new_sources_from_pmg.py
pombola/za_hansard/management/commands/za_hansard_run_parsing.py
pombola/za_hansard/models.py
pombola/za_hansard/parse.py

Adds a new management command to pull in sources from PMG's API.
Part of https://github.com/mysociety/pombola/issues/2458
After deploying the site, please run the following commands.

ZA Hansard updates
