- pombola/nigeria/templates/info/blog_list.html
When listing blog posts on the ShineYourEye blog the content is in raw
html, therefore we need to mark the html string as safe so that it will
render correctly.
I tried to write a test for this, but for some reason I couldn't reproduce the escaping but in the tests? Here's the code I put in `pombola/nigeria/tests.py`:
```python
from pombola.info.models import InfoPage
class InfoBlogListTest(TestCase):
def setUp(self):
InfoPage.objects.create(slug='escaping-test', kind='blog', title='Escaping Test', markdown_content="\nTesting\n\nEscaped\n\nContent")
def test_html_not_escaped(self):
response = self.client.get('/blog/')
self.assertNotIn('&ltp&gt', response.content)
```
However the test seems to pass before and after the change in this pull request, so I'm not sure what I've done wrong! …
> SYE: Make blog list content as html safe

- pombola/south_africa/templates/home.html
- requirements.txt
This updates django-pipeline to a version which uses `text/javascript` in the type attribute on script tags. It fixes the carousel in IE 8.
Fixes #1577
> ZA Internet explorer fixes

- pombola/settings/base.py
If there are no loggers defined for the elasticsearch Python package you
get errors like the following:
No handlers could be found for logger "elasticsearch" (in production)
No handlers could be found for logger "elasticsearch.trace" (local dev)
(I'm not sure why there's that difference in those logger names.)
This commit sets up loggers for both names in the Django settings module
that will send any logging of level INFO and above to standard error.
This suppresses that warning and should mean that we're able to see
real warnings and errors in the logs.
> Suppress the warnings about missing loggers for elasticsearch

- pombola/core/models.py
Previously this query was creating two inner joins for the same table,
which seemed to be causing postgres to never return from the query.
This change uses Q to OR together the two querysets which seems to work
correctly.
The query that is now produced by this method is:
```sql
SELECT DISTINCT "core_organisation"."id", "core_organisation"."created", "core_organisation"."updated", "core_organisation"."name", "core_organisation"."slug", "core_organisation"."summary", "core_organisation"."kind_id", "core_organisation"."started", "core_organisation"."ended", "core_organisation"."_summary_rendered"
FROM "core_organisation"
INNER JOIN "core_organisationkind" ON (
"core_organisation"."kind_id" = "core_organisationkind"."id"
)
INNER JOIN "core_position" ON (
"core_organisation"."id" = …
```
> Fix query that was running infinitely

- pombola/info/models.py
- pombola/info/tests.py
There was a problem that content after embedded videos (included via
YouTube's suggested <iframe ...></iframe> HTML) wasn't being displayed.
This turned out to be because we pass the raw HTML through lxml to
ensure that the output is well-formed, but this was converting empty
tags to self-closing tags and <iframe .../> and that eats the following
content in the page.
Adding method="html" to lxml.etree's tostring function preserves the
separate close tag.
Fixes #1608
> Don't convert empty tags to self-closing tags in raw HTML blog posts

- pombola/core/management/commands/core_fix_sayit_speakers.py
- pombola/core/management/commands/core_merge_people.py
- pombola/south_africa/views.py
We have changed the form of IDs in the South African PopIt instance
several times, but without removing the entries corresponding to old
PopIt IDs from the popit-django popit_person table. This meant that the
name resolution on importing new committee proceedings could associate
the speeches with various SayIt speakers corresponding to different
entries in that table.
This pull request introduces a script to hopefully clean up that mess; it
tries to remove any row with an deprecated format ID from the
popit_person table, safely removing any SayIt Speaker associated with
that row.
This should fix #1597 and hopefully #1601.
The underlying issue (that Pombola ZA stores the identity of people in
five different places) is being addressed by #1594.
> Add a script to fix inconsistent references to people from SayIt speakers

- pombola/south_africa/templates/menu_entries.html
This pull request is ready for when we're happy with the content of the page,
which is live now but not linked-to.
> Add a link to the API help page

- pombola/south_africa/templates/core/organisation_detail.html
- pombola/south_africa/views.py
Despite the careful use of select_related and prefetch_related in
pombola.core.views:OrganisationDetailView, the loading of an
organization with even a small number of people in it generate a huge
number of queries.
This is caused by the additional information requested by the South
African override of core/person_list_item.html, which does two costly
operations:
1. Finding places associated with that person by iterating over
position_set.all.current_unique_places and then accessing
parent_place for each of those too.
2. Calling the 'parties' method on each person, which creates a new
queryset for each person.
Neither of these are all that easy to make more efficient while still
providing the same information without restructuring a lot of the
template code, so instead this commit just …
> ZA: Reduce queries used on the organisation detail page

- requirements.txt
In edd668252b8b44d82b56 I upgraded elasticsearch, but didn't take into
account that the newer elasticsearch is only for Elasticsearch 1; we have
to stay on a version in the 0.4 series since we use Elasticsearch 0.9 on
our servers:
https://github.com/elasticsearch/elasticsearch-py#compatibility
This was causing the errors:
```
org.elasticsearch.indices.InvalidTypeNameException: mapping type name [_mapping] can't start with '_'
```
... on reindexing; this is due the URLs used when putting a mapping
having changed between Elasticsearch 0.9 and later versions,
e.g. compare:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/indices-put-mapping.html
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-put-mapping.html
Thanks to Matthew Somerville for …
> Fix elasticsearch version mismatch, which caused errors on reindexing

- pombola/search/search_indexes.py
- pombola/search/templates/search/hansard.html
- pombola/search/urls.py
- pombola/search/views.py
Fixes #1607 
* Adds a new field to `HansardEntryIndex` so that `start_date` is available to the sort function.
* Adds a drop-down box to the Hansard search form offering Sort by 'Relevance' (default), 'Oldest first' or 'Newest first'
I traded the `haystack.views` based `SearchView` for `HansardSearchView` which is a cut-down version of `SearchBaseView` minus sections and template_name resolution, mostly because trying to add `sort_by` to `SearchView` was giving me a headache. On the plus side, there is now scope to standardise the look of the Hansard search by including the existing partial templates for result items and pagination but I've avoided this in the first instance in case it introduces unwanted UI changes.
> Mzalendo: add date sort options to hansard search

- pombola/south_africa/fallback_urls.py
- pombola/south_africa/templates/south_africa/hansard_index.html
- pombola/south_africa/views.py
Adds pagination controls to the Hansard and Committee Minutes pages (they're derived from the same Index view).
Formulates the Sections queries in a top-down manner rather than the previous drill-up strategy. No longer retrieves individual Speech entries as only the speech counts are used by the display template.
Force groups the subsections by named section in SQL to remove duplicate section names as this was causing uneven pagination effects where one page could be 3 sections or more longer than expected while the next page may only consist of 2 sections. As this strategy has a knock-on effect of occasionally creating a really long list of subsections - which results in a large number of database lookups to render the links - the page length for Hansard listings has been shortened from …
> ZA: Paginate Hansards page

- pombola/south_africa/templates/core/person_detail.html
- pombola/south_africa/tests.py
- pombola/south_africa/views.py
Fixes #1602
* Inserts date of death at the top of the summary box, if applicable
* Retains the person's party affiliation if the deceased's membership has ended
* If there is only one current position (this is lazily assumed to be a party membership) - or nothing at all - to display on the profile summary, positions within "important organisations" + Electoral List positions will appear under the heading "Former Positions" (this should exclude party and committee memberships to avoid duplicating the contents of the Experience tab, especially where there is a long list of former positions)
> ZA: update person profile page

- pombola/core/context_processors.py
- pombola/kenya/templates/menu_entries.html
Overrides the core template to suppress the references to daily data dumps and "a number of ways of accessing ... data" if `dump_base_path` is not included in the view context
Note to self/deployer - relies on setting a valid `POPIT_API_URL` in the site config
> Add API help page for Mzalendo

- pombola/south_africa/templates/core/person_detail_position.html
- pombola/south_africa/templatetags/za_election_list_links.py
On profile pages, the link to e.g. "3rd Candidate at Inkatha Freedom
Party National Election List 2014 (Election List)" were resolving to
blank pages as an Election List is only valid for a short time and will
have no associated members once the election is complete. This change
replaces these links (except in the case of a "Regional" election link
which look as though it may be a duplicate of "Provincial" election data)
with a link to the appropriate election candidate list instead.
Fixes #1603
> ZA: Replace election list org links with links to election candidate lists

- pombola/hansard/kenya_parser.py
- pombola/hansard/management/commands/hansard_process_sources.py
- pombola/hansard/tests/test_kenya_parser.py
Adds a new reg exp for Joint Sitting headings and attempts to parse the start time from the accompanying "fifty five minutes past Two o'clock" style format.
Have also made a few tweaks to the reg exps for Senate and National Assembly sittings which should help to scoop up a few cases where Venue wasn't being picked up properly having notice that Senate sittings can also be written as "The House met at 2.30 p.m. in the Senate Chambers" (as opposed to the expected string "The Senate met....".
Fixes #1645
> Mzalendo: allow Hansard parser to deal with Joint Sittings

- pombola/experiments/views.py
- pombola/kenya/urls.py
- pombola/kenya/views.py
The views used for the County Performance experiments could be
reused for other similar pages, but several properties of those
experiments were hardcoded in the views. In addition, it makes
sense for the generic view code to be in the experiments application
instead of kenya.
> Make the survey / experiment views easier to reuse

- pombola/core/models.py
- pombola/kenya/templates/core/person_experience.html
* Adds `committees` and `exclude_committees` filters to `PositionQuerySet`
* Excludes committee memberships from the existing sections and groups them into a new **Committee Memberships** which sits in the lefthand column, under **Previous Political Positions**
The new committee filter checks whether the organisation's slug contains 'committee' which may ultimately prove fragile, but I couldn't see a more reliable option.
Closes #1643
> KE: Move committee memberships to own section on profile pages

- pombola/experiments/views.py
- pombola/kenya/templates/county-performance.html
- pombola/kenya/templates/youth-employment.html
- pombola/kenya/tests.py
- pombola/kenya/views.py
All the data that MIT want is being stored in our database, and we're
not using Google Analytics for anything except picking a random variant
of the page.  Using it for randomization also has a few difficulties:
* It does a redirect after the page load, and sometimes we don't seem
to be getting that redirect (because of Javascript failures or
network problems, we assume)
* There's not a natural goal we can set for the content experiment, so
we've just been setting 99.5% confidence that one variant increases
page views across the site as a whole, which is unlikely to happen
and stop the experiment, but still seems silly.
* The code in the view is unnecessarily complicated to deal with
essentially ignoring page views without a utm_expid.
So, this commit switches to picking a variant …
> Stop using Google Analytics' Content Experiments for randomizing pages

- pombola/search/templates/search/location.html
- pombola/search/tests/views.py
- pombola/south_africa/templates/search/location.html
- pombola/south_africa/tests.py
This adds a submit button to the location search form and applies the search form stylings that are used elsewhere.
It should also prevent a blank map from being displayed when there are no search results
(Applies to the base search/location template as well as the custom template for South Africa)
Fixes #1657
> Fix location search form layout

- pombola/nigeria/tests.py
- pombola/nigeria/views.py
This was breaking because the regex that was checking for a valid
PU number was expecting a PU formatted string and we were passing
it the raw query instead, so the PU lookup was being bypassed
unless the search string took the form of OD:1:2.
Although we don't do anything with the last part of a full 4 part
PU number, we are now accepting the full 01:02:03:04 format as
input for our PU number lookup.
Fixes #1675
> Fix the ShineYourEye PU number lookup

- pombola/south_africa/management/commands/south_africa_adwords_csv.py
Writes out 4 csv files with data for representatives, provinces, parties and constituency offices.
The queries involved have less common ground with https://github.com/mysociety/pombola/blob/master/pombola/kenya/management/commands/kenya_adwords_csv.py than I expected (although I may well have missed the obvious here) so I have not attempted to pull out the common functionality into a base adwords_csv command.
Fixes #1683
> ZA: Add management command to generate adword csvs

- pombola/core/static/js/analytics.js
- pombola/templates/default_base.html
GA is not blocking (the original reason for it being lazy), and this allows GA to detect the tracking code and stop complaining.
* Closes #1707
nb This keeps extra print event tracking (in analytics.js) as lazy and compressed, since the `ga` object will be initialised by that point anyway.
> Move Google Analytics JS to static page, rather than lazy-loading.

- pombola/kenya/templates/header.html
- pombola/settings/kenya_base.py
Pulls the now complete Quant 1 research survey from display on Mzalendo.
Some elements remain, as they're also used for the ZA survey.
> Remove research survey from Mzalendo

- pombola/kenya/static/sass/_kenya_overrides.scss
- pombola/kenya/templates/core/person_base.html
Using 'white-space: pre' causes addresses that are formatted without
linebreaks to be displayed as a continuous line which breaks the
layout of the person pages. This commit uses Django's linebreakbr
filter to force linebreaks in the address text to be rendered as
`<br>` tags instead.
Fixes #1700
> KE: Retain linebreaks in address data using template filters not CSS

- pombola/nigeria/templates/menu_entries.html
Adds link to "Events" between the main navigation, between "Places" and "Blog" (which feels right as there is no subnavigation).
I have also removed the "This is an example of an events page (not currently linked to from the main navigation)" and the duplicate header from the Events infopage in the ShineYourEye admin.
I have noticed that the breadcrumb for that page is Home >> Information >> Events where clicking on Information results in a 404 (the already published About page has the same issue), which is not ideal.
Also we should probably check back with ShineYourEye to make sure the Events page is ready for launch before we deploy.
Fixes #1694
> NG: Add events link to main site nav

- pombola/core/models.py
- pombola/core/tests/test_organisation_kinds.py
- pombola/core/views.py
- pombola/slug_helpers/views.py
Use SlugRedirectMixin to allow an old organisation kind slug to
redirect to a replacement slug.
If this change is accepted, #1669 just needs a row adding to the slug redirects table to redirect the  'political-party' `OrganisationKind` to 'party'.
> Allow slug redirects for OrganisationKinds.

- pombola/core/static/css/jquery.ui.datepicker.css
- pombola/core/static/js/libs/jquery.ui.datepicker.js
- pombola/core/static/sass/_search.scss
- pombola/search/templates/search/search_base.html
- pombola/search/views.py
- pombola/settings/south_africa_base.py
- pombola/south_africa/static/js/advanced-search.js
- pombola/south_africa/tests.py
Adds the date range params and logic to the core search so that it's available for all countries if required but the new UI elements have only been added for South Africa so far.
49e167e also fixes an incidental bug which meant that "Sort by date" was offered to users for the global as well as per-section search but wasn't actually changing the sort order. However this can produce unexpected result ordering where some of the results do not have applicable dates (more detail in commit message).
Fixes #1681
> ZA: Add search range filter to search

- pombola/nigeria/templates/search/poll-unit-number.html
- pombola/nigeria/tests.py
- pombola/nigeria/views.py
This changes the PUN search so that it displays whether it matched the PUN at a state, LGA or ward level, and always displays the name of the containing state of the search results.
Adds the name of the current representative for the overlapping districts, where available (or the text 'no current representative' where the representative's name is not held).
Fixes #1714
> NG: Return more detailed info in PUN search

- pombola/south_africa/templates/south_africa/ward_councillor_lookup.html
- pombola/south_africa/urls.py
This isn't ideally how we'd like to incorporate this lookup, since
it depends on Javascript and uses an iframe, but there's some time
pressure on adding this feature and Code4SA have made it very easy
with this widget.
Fixes #1730
> Add the Code4SA ward councillor widget

- pombola/core/management/commands/core_merge_people.py
- pombola/core/models.py
- pombola/core/tests/test_commands.py
- pombola/core/tests/test_models.py
- pombola/hansard/management/commands/hansard_reattribute_entries.py
- pombola/hansard/tests/test_reattribute_entries.py
Fixes a bug in the `core_merge_people` management command which was preventing it from picking up hansard speeches and interests register information. Also provides more data to the user and offers them the choice of whether or not to continue once both speakers have been identified (with a specific warning if both speakers turn out to be the same person - i.e. if one is an alias of the other).
Adds a new management command, `hansard_reattribute_entries` which takes 2 person identifers and optional to and from dates in order to assign one person's speeches to another. Does not attempt to delete the donor speaker from the database even if this leaves them with no contributions.
Both commands will now accept either a numeric person id (as before) or a slug.
Partially fixes #1712 (won't be …
> Better Hansard speech reattribution functionality

- pombola/hansard/models/entry.py
- pombola/hansard/tests/test_entry.py
Attempts to deal with ambiguous speaker names such as "Hon. Nanok" which will match 2 current Kenyan politicians (the parser happens to be consistently picking the "wrong" one) by attempting to add a 'member of current house' restriction if more than 1 name is matched
Fixes #1743
> Better Hansard speaker matching

- pombola/hansard/constants.py
- pombola/hansard/management/commands/hansard_assign_speakers.py
- pombola/hansard/models/__init__.py
- pombola/hansard/models/entry.py
- pombola/hansard/tests/test_kenya_parser.py
- pombola/settings/base.py
- pombola/settings/kenya_base.py
Add a setting to allow the Hansard name matching algorithm to be changed per country - this means Kenya can carry on doing it the old way, while we use the new improved algorithm for Ghana.
Fixes #1719
> 1719 name matching algorithm settings

- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/home.html
https://github.com/mysociety/pombola/issues/1670#issuecomment-136663910 raised the issue of the infographics on the homepage being too low down, and being cut off on short desktop screens.
To some extent this can't be helped for ultra-short screens (ie: 600px high or less) – the People's Assembly header and nav bar alone take up 150px.
But I've attempted to improve the situation for screens in the middling category – somewhere between 600px and 800px high. For a drastic comparison, here's before (left) and after (right), at 650px high:
700px high:
And 750px high:
Note how more of each infographics is visible on page load, so people know they can scroll down.
> ZA: Improve homepage spacing on short but wide screens

- pombola/core/tests/test_positions.py
- pombola/core/views.py
Allow position title urls to use slug redirects. This means that if someone edits a slug of something for which the slug is baked into the templates, we can keep all the urls that were ever in use pointing at the right place.
This is the code part of the fix for #1737.
Connect to #1737
> Allow slug redirects for PositionTitles.

- pombola/south_africa/templates/home.html
The four infographic previews on the homepage are cropped so that only the top 250px are included, and also given 80% JPEG compression (down from the default 95%).
On my VM, this represents a roughly 90% saving in file size (from 120KB each image, down to 14KB).
> ZA: Crop and compress homepage infographic previews

- pombola/core/templates/core/object_base.html
- pombola/core/tests/test_views.py
- pombola/kenya/templates/core/object_base.html
This affects all instances of Pombola that don't override this part of `object_base.html` (all except Mzalendo, as far as I can tell)
> Use srcset for people photos

- pombola/info/tests.py
- pombola/info/views.py
- pombola/south_africa/templates/info/_blog_sidebar.html
In combination, these commits take the time for the SQL on blog pages
down to 0.1 second from about 30 seconds.
> ZA: fix the astonishingly slow display of blog pages

- pombola/core/logging_filters.py
- pombola/settings/base.py
We get quite a lot of UnreadablePostData errors by email from Pombola
sites.  We believe that these represent POST requests (often large
updates) that were interrupted by network problems of one kind or
another, in which case this is just email noise and we should suppress
them.
My only concern about suppressing these emails is that we also got a lot
of these error emails from AJAX POST requests that were a "heartbeat" to
measure how long people spent on the MIT experiment pages (e.g. POSTs to
/youth-employment/youth-employment/time-on-page) - these might be
problems with AJAX on particular browsers, but we never figured that
out at the time, and suppressing these error emails might means we're
less likely to notice them and investigate in the future.
Fixes #1433
> Don't send emails on UnreadablePostData errors

- pombola/core/static/sass/_page.scss
- pombola/core/templates/core/object_base.html
- pombola/core/templates/core/person_base.html
- pombola/kenya/static/sass/_kenya_overrides.scss
- pombola/kenya/templates/core/object_base.html
- pombola/kenya/templates/core/person_base.html
- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/base.html
- pombola/south_africa/templates/core/person_detail.html
- pombola/south_africa/templates/core/person_speech_list.html
- pombola/south_africa/tests.py
- pombola/south_africa/views.py
- pombola/templates/default_base.html
Fixes for #1807.
Sorry for the seeming grab-bag of changes. I’ll try to summarise them here, but if you think some squashing/splitting of commits would make it clearer, go ahead and do it.
1. Move the person details back into the sidebar (like they are in core) and remove styling for the horizontal green section that used to hold those details.
2. Show region (rather than a list of memberships) under the person's name.
2. Tweak the display of the "Appearances" section, as per PMG's feedback:
* Order: committee appearances, then questions, then plenary
* Number: 5 committee appearances, 3 questions, 2 plenary attendances
* If questions list is empty show "No questions found" rather than "No speeches found"
1. On the desktop view of the person page, replace the absolutely-positioned layout …
> Peoples Assembly person page tweaks

- pombola/core/static/sass/_search.scss
- pombola/search/templates/search/search_base.html
- pombola/south_africa/static/js/advanced-search.js
- pombola/south_africa/static/sass/_south-africa_overrides.scss
Fixes #1834.
Adds an "Update results" button to the advanced search form on all Pombolae, and improves the layout on People’s Assembly in particular by folding all the inputs onto just two lines in desktop view.
Here's a before and after:
The disabled "Update results" button is reactivated when any of the advanced inputs are changed:
However, because the button is disabled by javascript, there is a noticeable period on pageload where it is bright red. Any ideas @mhl?
> "Update results" button on advanced search page

- pombola/core/static/js/survey.js
- pombola/core/static/sass/_header.scss
- pombola/settings/base.py
- pombola/south_africa/templates/header.html
Displays [a new survey](https://www.surveygizmo.com/collab/2458850/People-s-Assembly-Indigo-Trust-Impact-Survey) (although identical in most regard to the previous one) to 40% of site users.
This is to track impact for Indigo Trust.
> Add survey link for Indigo Trust impact survey to ZA.

- pombola/core/models.py
- pombola/core/tests/test_positions.py
- pombola/south_africa/templates/core/person_detail.html
- pombola/south_africa/views.py
Add memberships of Provincial Legislatures to the tagline on a person page (closes #1857). This is done by changing how we decide which positions are important to work off the slug of the organization kind rather than off the organization. In future we could make this piece of configuration data by having a table of ids of org kinds which are this sort of important in the database and editable by the Django Admin.
Also adds former memberships of important organizations (closes #1856).
Finally, I've removed some of odd bits of code which weren't used anywhere else.
I suggest we don't actually put this live until we've added some better testing of the person detail page and also fixed the problem in #1878.
> 1857 more positions in tagline

- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/site_header_logo.html
Fixes #1849.
Also includes a few overdue fixes to the horizontal padding / gutter either side of the header elements on mid-size screens, and the overcomplicated layout that the "about-this-site" menu items used to have.
Large screen:
Mid-size screen: (this is at its absolute worst – 640px)
Small screen:
> ZA: Social media links in header

- pombola/south_africa/tests.py
- pombola/south_africa/views.py
This sorts out NCOP delegates not appearing in the right place, which was caused by the position having title 'delegate' rather than member. The code has loads of places which make allowance for NCOP positions being delegates rather than members, so I don't really want to just switch it to member as it might well break some.
It would be nice to generally reduce the number of places the code refers to particular slugs.
At the moment this causes another test to fail. There is a check to make sure that if someone is both a member of the National Assembly and a delegate to NCOP that they don't appear on the list for the place twice. I would like to know if this is a real possibility, and if not, that test could be cut.
Fixes #1886.
> 1886 ncop grouped as other

- pombola/kenya/templates/core/person_base.html
- pombola/kenya/tests.py
- pombola/kenya/views.py
These changes should hopefully stop duplicate constituencies/counties appearing on the sidebar on the person detail page (#1838). There should now be at most one constituency for NA members, and one county for senators.
This is currently done in the view and template layers for KE only. It would be good in the long run to have a system for storing which combinations of organisation, organisationkind, positiontitle, etc should be considered important enough to display here, and storing that in the database rather than the code.
> 1838 important orgs

- pombola/core/lookups.py
- pombola/hansard/models/alias.py
- pombola/settings/base.py
People who have 'hidden' set to True are people who have stood for an
election but essentially zero chance of ever having appeared as a
speaker in Hansard.  Since there were Alias objects referring to hidden
people, let's prevent this from being possible.
> hansard: Fix for it being possible to create aliases to hidden people

- pombola/south_africa/templates/menu_entries.html
Removing Impressions and Elections 2014 from the Blog menu drop down items on people's assembly
Fixes #1919
> Removing items from blog menu dropdown on pa.org.za

- pombola/core/admin.py
This was prompted by an error email we were getting, and includes
a fix for some missing HTML-escaping in the link generation.
> Fixes for admin link generation errors

- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/south_africa/mp_attendance.html
This displays a temporary notice to users until it is determined how treat faulty attendance records for members of small parties.
The API has been updated to returns results as the notice stipulates.
> Display notification message on attendance page

- pombola/search/templates/search/items/person.html
> [NG] Don't show organization name unless there is one

- pombola/core/templates/core/organisation_detail.html
> Pluralize is/are in organisation contact details in overview.

- pombola/core/templates/core/position_detail_grid.html
> Remove link on grid view to view past positions

- pombola/core/templates/core/person_position_section.html
- pombola/kenya/templates/core/person_detail.html
- pombola/kenya/templates/core/person_detail_experience_list.html
We were saying people had no experience when actually what we meant was
the person had no current positions that we know about. This changes the
text on person pages to make that clearer.
Fixes #1983 (paired with @duncanparkes)
> [KE]: Fix misleading "No experience" claim

- pombola/core/templates/core/place_detail.html
- pombola/south_africa/templates/core/place_detail.html
Fixes #2044 (paired with @chrismytton)
Relates to #2061 
Manually adding a CDF project to kaiti-2013 to check the pluralization:
> 2044 clumsy wording no cdf

- pombola/core/models.py
- pombola/core/tests/test_models.py
This adds a 'fields_to_whitespace_normalize' property to models which
can be set to a list of fields which should have their whitespace
removed before the model is saved.
First part of #1866
> Models can define fields to be whitespace stripped

- pombola/templates/default_base.html
Rather than linking to the GitHub repo link to the mySociety site which
has a better explanation of Pombola and the problems it solves.
Fixes https://github.com/mysociety/pombola/issues/1905
> Link to a more descriptive page in the footer

- pombola/core/urls.py
- pombola/core/views.py
This returns the current Python, Django and git version for a Pombola site.
Fixes #1946
> Add /version.json endpoint

- bin/prepare_environment.bash
This is no longer needed now we're not installing GDAL.
Fixes #869
> Remove --system-site-packages from virtualenv args

- conf/crontab.ugly
This alias is logged in Google Groups and goes to Jess and the rest of
the Mzalendo team.
Fixes #1582
> Send update_hansard cron emails to mzalendo-managers

- pombola/south_africa/templates/south_africa/hansard_index.html
Adds a search box to the Hansard page. This acts like the regular search, but restricted to Hansard results.
Fixes https://github.com/mysociety/pombola/issues/1846
> ZA: Add a search box to the Hansard page

- pombola/core/templates/core/social_tools.html
The Disqus link previously always went to a person, but the comments box can appear on orgs and places as well. This changes the link to a relative link using a url fragment.
Fixes #1460
> Use a relative link to Disqus comments from social tools

- .travis.yml
This should speed up builds significantly.
Fixes #2088
> Cache pip dependencies on Travis CI

- pombola/kenya/management/commands/kenya_assign_aspirants_to_coalitions.py
Since we merged the 'ford-k' party with 'ford-kenya', we don't need this slug in this script any more.
Fixes #2111
> Remove 'ford-k' slug from parties list.

- pombola/core/context_processors.py
- pombola/core/templates/core/_person_open_graph.html
- pombola/core/templates/core/organisation_base.html
- pombola/core/templates/core/person_base.html
- pombola/core/templates/core/place_base.html
- pombola/core/tests/test_open_graph.py
- pombola/core/tests/test_views.py
- pombola/info/templates/info/_blog_open_graph.html
- pombola/info/templates/info/blog_post.html
- pombola/kenya/templates/core/person_base.html
- pombola/nigeria/templates/info/blog_post.html
- pombola/settings/base.py
- pombola/south_africa/templates/info/blog_post.html
- pombola/south_africa/tests.py
- pombola/templates/default_base.html
This adds some default Open Graph tags to all pages on the website. It also adds specific Open Graph tags for Organizations, Places and blog posts.
Fixes https://github.com/mysociety/pombola/issues/2047
Fixes https://github.com/mysociety/pombola/issues/2048
Fixes https://github.com/mysociety/pombola/issues/1956
Fixes https://github.com/mysociety/pombola/issues/1955
> Open Graph tags

- pombola/south_africa/views.py
A bad query is somehow getting through the Django ORM to postgres.
The first occurrence of this is on 2016-03-05, which is a couple
of days after we upgraded to Django 1.8, so I imagine it's
something that's changed in the ORM.
Postgres is complaining that a field which is has a distinct on it
needs to be the first in the order by, so I've added an order by
for this field.
Fixes #2109.
> Order by person__id when it's going to be used in distinct.

- pombola/core/management/commands/core_find_stale_elasticsearch_documents.py
The first two commits improve `core_find_stale_elasticsearch_documents` as a
tool for investigating the stale search index entries problem. The final commit
adds a option for fixing those issues as they're found. More background from
the commit message below:
There is an as yet unsolved problem where an object in the database
has been deleted, but there is still a stale Elasticsearch document
that refers to it; for some reason Haystack hasn't got the signal
to remove it.
We were fixing this synchronisation problem by running
`./manage.py rebuild_index`, but that takes a really long time to run
and means search will be missing results while it's running (since it
clears all the indices, and we haven't implemented
zero-search-downtime-reindexing of Elasticsearch yet).  This commit
adds a …
> Improvements to core_find_stale_elasticsearch_documents

- pombola/core/admin.py
Place pages (both the list and the detail) in the admin were incredibly
slow because they were making thousands of queries. This is because the
__unicode__ methods of Place and Organisation use related objects.
There are two changes here:
* get_queryset - This is used for the list page.
* get_field_queryset - This is used to create the querysets for
populating the select elements for foreign keys on the detail
page.
So the former speeds up the place page, while the latter speeds up the
detail page.
Fixes #2085
> Greatly reduce queries needed for Place pages in the admin

- pombola/core/static/js/loader.js
In production we were getting an error that suggested that tabs.js was
being loaded before map.js.
These are loaded by different mechanisms (warning: this is all awful):
- map.js is loaded via `{% javascript 'google-map' %}` in the `<body>`
which is replaced by a `<script>` tag that loads it directly
- tabs.js is loaded from the 'both' case of yepnope (although in a
slightly convoluted way, because of the hack to make django-pipeline
work with yepnope) - it starts with `addExtraJS`
I believe this is happening because the files that are loaded from
'both' don't wait for the document to be ready, so the `<script>` tag in
the body might not have been loaded yet.
This moves the loading of the extra JS into the `complete` callback of
yepnope, and wraps the body of that function in …
> Make sure JS files from addExtraJS are loaded after in-page <script>s

- pombola/core/templates/core/person_base.html
- pombola/kenya/templates/core/person_base.html
We'd like the EveryPolitician scraper to be able to extract the Pombola
person ID in a predictable way - this commit adds that value in a
`<meta name="pombola-person-id">` in the `<head>`.
Fixes #2130
> To help the EP scraper, add the person ID in a <meta> tag

- pombola/settings/base.py
- pombola/wsgi.py
Merging the `heroku` branch introduced a couple of errors that
only became apparent in production:
* Loading the config in `wsgi.py` was failing
* The `STATIC_ROOT` directory was accidentally and unnecessarily changed
These commits fix those issues.
> Fix errors when deploying to production

- pombola/core/management/commands/core_import_kenyan_boundaries_2013.py
- pombola/core/management/commands/core_match_places_to_mapit_areas.py
- pombola/core/management/commands/core_match_places_to_mapit_areas_2013.py
- pombola/kenya/migrations/0001_fix_mapit_area_types.py
- pombola/map/templates/map/home.html
- pombola/south_africa/templates/map/home.html
MapIt does allow type codes that have lower-case letters, but they can't
then be looked up with, for example:
/mapit/areas/ctr.html
This commit migrates the MapIt area types to have upper case codes, so
that these helpful API endpoints are usable again.  It should change all
references to these types in the code as well.  (I checked for uses of
ctr|pro|div|loc|sub|con|dis to update.)
We've never advertised the Mzalendo MapIt, so there shouldn't be any
external users of the API who would be affected.
Fixes #495
> KE: fix MapIt area type codes (they should be uppercase)

- pombola/south_africa/tests.py
- pombola/south_africa/views.py
The site has gone down a few times recently, and we suspect this was
because of workers being tied up waiting for external services that are
timing out.  To hopefully reduce the effect of such outages, this commit
times-out any such requests after three seconds.
Fixes #2174
> ZA: add a 3 second timeout to HTTP requests to external services

- pombola/core/management/commands/core_export_to_popolo_json.py
- pombola/core/migrations/0004_parliamentarysession_position_title.py
- pombola/core/migrations/0005_parliamentarysession_make_house_optional.py
- pombola/core/models.py
- pombola/core/popolo.py
- pombola/core/static/sass/_listing.scss
- pombola/core/templates/core/_position_session_links.html
- pombola/core/templates/core/position_detail.html
- pombola/core/templates/core/position_detail_grid.html
- pombola/core/templates/core/session_list.html
- pombola/core/tests/test_models.py
- pombola/core/tests/test_views.py
- pombola/core/urls.py
- pombola/core/views.py
- pombola/country/__init__.py
- pombola/kenya/lib.py
- pombola/kenya/migrations/0002_adjust_parliamentary_sessions.py
- pombola/kenya/migrations/0003_remove_senate_organisation.py
This will produce slightly confusing results at the moment because the 2007 -> 2013 parliamentary session object is associated with the National Assembly organisation, when really it should be associated with Parliament with the current way it's modelled. https://github.com/mysociety/pombola/issues/2092 is related. However, we can fix that after deploying this, I think.
> Add filters for viewing positions from particular parliamentary sessions

- conf/crontab.ugly
- pombola/kenya/management/commands/kenya_check_for_recurring_problems.py
At the moment this just deals with two types of common data error:
Positions with the title 'Member of the National Assembly' where the
organisation is anything other than 'Parliament'
Positions with the title 'Member of Parliament' where the organisation
is anything other than 'Parliament'
... but the intention is to add other checks.  The crontab is updated to
run this every night - there will only be output if any problems were
found.  Some problems may need to be fixed by hand, but the script has
an option to fix common errors discovered by the script.
Fixes #2064
Fixes #2065
> Add a command to check for (and optionally fix) common data problems

- pombola/hansard/fixtures/hansard_test_data.json
- pombola/hansard/tests/test_sitting.py
- pombola/hansard/views.py
Sitting.get_absolute_url would omit the start_time suffix if
start_time was None, but the SittingView would interpret that
URL as referring arbitrarily to the first sitting in that venue
on that date.  This meant that appearances might link to the
wrong sitting, confusingly.
This commit changes that logic so that if the start_time is
missing, it looks for a sitting with start_time None.
Fixes #2195
> Links generated to a sitting should actually show that sitting

- pombola/core/templatetags/clean_html.py
- pombola/core/tests/test_clean_html_templatetags.py
This should remove HTML that might be dangerous (e.g. script tags)
> Add a template tag for "cleaning" HTML using lxml.html.clean

- pombola/south_africa/templates/info/_blog_sidebar.html
- requirements.txt
This PR shows recent posts only in the popular posts section of the sidebar.
PMG requested to show only posts that were published during the
last month in the popular posts section of the sidebar shown in blog pages.
Fixes #2212
> [ZA] Fix recent blog posts

- pombola/core/static/sass/_search.scss
- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/core/organisation_people.html
- pombola/south_africa/templates/core/position_detail.html
Fixes #2216.
The search box at the top of the "MP Profiles" page now matches the main search page:
> Consistent styling for `.people-list-inline-search`

- pombola/settings/base.py
- requirements.txt
./manage.py shell_plus, from django-extensions, is very useful and a
great time-saver, but there are plenty of model name collisions among
all the Django applications used by Pombola - this commit uses the
SHELL_PLUS_APP_PREFIXES setting to disambiguate those, adding a prefix
to the generally less commonly used application.
> Disambiguate the model names automatically imported by shell_plus

- pombola/core/templatetags/get_from_key.py
- pombola/core/tests/test_templatetags.py
- pombola/south_africa/templates/info/_blog_sidebar.html
- requirements.txt
The posts must be tagged with a tag whose slug is `must-read`
in order to appear there.
This change updates the django-info-pages package so that we
can use `posts_by_tag`.
We also added a new template tag to the core template tags
which allows us to return the value corresponding to a key when it
contains characters that are not allowed in template variable
names like `,`, `.`, `-`, etc. since it is very common to have dashes in
tag slugs.
Fixes #2213
> ZA: Show 'must read' posts in sidebar

- pombola/settings/base.py
- pombola/south_africa/templates/header.html
Comments out the survey JS, as no other Pombola sites are running a survey right now. Leaves CSS, since surveys may come back and it’s tiny.
> Remove the survey banner from pa.org.za.

- pombola/core/models.py
- pombola/core/templates/core/_alphabetical_pagination.html
- pombola/core/templates/core/position_position_section.html
- pombola/core/templatetags/add_query_parameter.py
- pombola/core/tests/test_templatetags.py
- pombola/core/tests/test_views.py
- pombola/core/views.py
- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/core/organisation_people.html
- pombola/south_africa/templates/home.html
- pombola/south_africa/templates/menu_entries.html
- pombola/south_africa/views.py
This PR:
* Adds a new template tag to add a query parameter to a URL in a template
* Moves the logic for showing an alphabet navigation from the South African views.py to the core so that it can be used elsewhere
* Adds a new query parameter to use in pages where we want to show the alphabet navigation `?a=1`. 
In the screenshot, you can see the url with the new query parameter and the MPs sorted by the letter C
Fixes  #2215
> South Africa: Add alphabet navigation to MP profile pages

- pombola/core/views.py
- pombola/south_africa/templates/core/position_detail.html
- pombola/south_africa/tests.py
This PR addresses the first part of #2221, in particular, deleting "any" from the header of the MP Profiles page.
Since this change affects only a particular page in a particular country, a conditional was added to the template that renders the MP Profiles page in the South African site to discriminate this particular page from other position pages.
For this conditional to work properly, a new item was added to the positions context in the core views so that it also sends the organization kind slug (`ok_slug`) to the template.
The tests cover the three branches of the condition.
> ZA: MP Profiles tiny header fix

- pombola/core/templates/core/_position_session_links.html
- pombola/south_africa/tests.py
This PR addresses the second part of #2221, in particular, deleting the subheader that reads "Current Position Holders" in the MP Profiles page.
Since this change affects only a particular page in a particular country, a conditional was added to the template that renders the MP Profiles page in the South African site to discriminate this particular page from other position pages.
The tests cover the three branches of the condition.
#2228 should be merged first. However, I have cherry-picked a commit from that PR that was needed for this PR (3075173). Hopefully once the other branch is merged, and this branch is rebased with master, that duplicated commit will dissapear.
Fixes #2221
> ZA: MP Profiles tiny subheader fix 

- .travis.yml
- run-tests
One of these commits adds a convenient `--coverage` option
to `./run-tests`, while the other uses that option on Travis and
reports the results to https://coveralls.io
> Add code coverage measurement and reporting

- pombola/hansard/templates/hansard/sitting_detail.html
- pombola/hansard/tests/test_sitting_view.py
- pombola/hansard/views.py
Allow admin users to select an option that will display the original
name of the speaker from Hansard next to the name we have matched
against. This should help to make debugging problems with aliasing and
speaker matching a bit easier.
> Add option to display original names of speakers

- pombola/core/views.py
- pombola/south_africa/templates/core/_person_position.html
- pombola/south_africa/templates/core/organisation_party.html
- pombola/south_africa/templates/core/organisation_people.html
- pombola/south_africa/templates/core/person_list_item.html
- pombola/south_africa/templatetags/za_people_display.py
- pombola/south_africa/tests.py
- pombola/south_africa/views/organisations.py
This hides place names and positions in people lists where they are either obvious (e.g. all Members of Parliament will have the position Member) or irrelevant (the province of an MP is not very useful).
It does this using template tags to check if the position or place is relevant for the organisation that is currently being displayed.
Fixes #2222
> [SA] hide obvious or irrelevant positions and places in people lists

- pombola/south_africa/templates/core/position_position_section.html
This removes the dropdown for only showing MPs by area as it's largely been made redundant by the improved search.
Fixes #2233
> ZA - remove place filter on MP profiles list page

- pombola/core/popolo.py
- pombola/core/tests/test_popolo.py
Added because it's useful when trying to reconcile this data in
EveryPolitician.
> include pombola-slug as identifier in json export

- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/south_africa/mp_attendance.html
- pombola/south_africa/views/attendance.py
These changes allow a user to filter the attendance by all MPs or only Ministers,
with the page defaulting to show the attendance of Ministers only.
Data received from the PMG API is matched with Persons by comparing part of the PA URL received with the slug field.
The Position's slug is also used to get Ministers and Deputy Ministers. `overlapping_dates` is used to include all active Ministers for the year being viewed.
A small edit to the text in the notification box has also been made.
> 2239 za filter attendance by minister

- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/south_africa/mp_attendance.html
- pombola/south_africa/views/attendance.py
This change excludes Ministers from the list when viewing the attendance of MPs.
If we cannot determine the `Position` of a `Person` (when the Members returned from the PMG API  has `pa_url=None`), we assume them to be an MP.
The average attendance for parties should only be displayed when viewing MP attendance, and not when viewing the attendance for Ministers, as their attendance is only encouraged and not  compulsory.
> MPs and Ministers are mutually exclusive

- pombola/south_africa/static/js/attendance-table.js
- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/south_africa/mp_attendance.html
- pombola/south_africa/views/attendance.py
This enables us to show an attendance of 0 for ministers without attendance records, and to only display a subset of columns for the ministers.
We get all the active Minister Positions from the DB as at the date of the query, or the year end. Whichever is earlier.
For the People associated with active ministerial Positions, for whom we didn't receive data from the PMG API, we add attendance records of 0. If we cannot determine a member in the API results to be a Minister, we assume them to be an MP.
We only show meetings attended for ministers, as attendance is not compulsory, and we don't want to give this impression by showing a ratio.
The filters and disclaimers have also been re-arranged on the page.
> 2247 minister attendance

- pombola/core/models.py
- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/core/person_detail.html
- pombola/south_africa/tests.py
- pombola/south_africa/views/attendance.py
- pombola/south_africa/views/person.py
This makes the attendance records on Person profiles consistent with the attendance listing page.
For an active ministerial position in a given year, we only display the number of meetings attended, and not a percentage
> Only show no of meetings attended for ministers on Person profile

- pombola/south_africa/views/attendance.py
Filter `attendance_summary` by excluding attendance records which are in `minister_attendance`.
This was previously done by removing items as we were iterating over a list. Which doesn't quite work as expected. And obviously so.
> Don't delete items while iterating over list

- pombola/settings/base.py
This pull request makes two changes to the use of templates in Pombola:
* It migrates from the deprecated `TEMPLATE_` settings to the new `TEMPLATES` setting
* It enables caching of templates the first time they're loading, so rendering a single template multiple times should be much faster.
> Move away from deprecated TEMPLATE_ settings and use the caching template loader

- pombola/settings/base.py
Templates were previously cached, no matter where the site was running, which meant restarting the `./manage.py runserver` process whenever you made a change to the HTML templates on a staging / dev site.
This commit disables the caching if the Staging flag is set.
> Disable Django template caching on Staging

- pombola/core/models.py
- pombola/south_africa/templates/core/person_detail.html
- pombola/south_africa/tests.py
- pombola/south_africa/views/attendance.py
- pombola/south_africa/views/person.py
As person's position can change at any time during a year, and attendance for ministers and MPs are reported differently, ministerial status should be checked at the date of each meeting.
A new API endpoint is used for data on the MP attendance page.
> 2271 new attendance api

- pombola/core/static/js/analytics.js
- pombola/south_africa/templates/home.html
Part of #2250. (Only _part_ because this is an experiment, so we should leave #2250 open until the experiment has finished.)
Template changes to hook up Google Analytics Experiment `VBriYVTaRiuLeNK8NimPCw` on the Peoples Assembly homepage. 50% of mobile visitors will be shown the following variation, with the "Hot topics" links at the _top_ of the homepage:
The success metric for the experiment is an increase in clicks on the "MP Profiles" button, so we also add some event tracking for that, using mySociety’s standard `trackEvent` wrapper.
The analytics "experiment" is already running, so data will start being collected as soon as this is merged and deployed.
> A/B test "Hot Topics" position to increase clicks on "MP Profiles" button on mobile

- pombola/south_africa/templates/core/person_detail.html
This is by urgent request from PMG. Attendance is far more of a hot topic in SA than appearances in committees, so they'd like it to come first. They have an article going out on Monday for which they'd like these changes.
They would also like to rename "Appearances" to "Comments and Questions", but that seemed like a larger and more controversial change (will the subheadings on that tab then change?), so I would like to get the swap in first.
> Swap Appearances and Attendance tabs

- pombola/south_africa/templates/home.html
Test if moving the hot topics buttons on the homepage results in any negative effects for other homepage interactions
- Doesn't currently test for input or button events, just links
- [Google Analytics experiment detalis](https://analytics.google.com/analytics/web/#siteopt-experiment/siteopt-experiment-wizard/a47810266w79169250p81872469/%3FcreateExperimentWizard.experimentId%3DiHAkMeOzSlerqgN8qLk8IA/)
> Adds a new experiment to People's Assembly homepage

- pombola/core/templates/core/object_base.html
- pombola/templates/default_base.html
In order for the [Facebook comments moderation tool](https://developers.facebook.com/tools/comments/1619725741628189/pending/descending/) to work correctly this meta tag needs to be on all pages that contain the comment widget, more details [in the documentation](https://developers.facebook.com/docs/plugins/comments#moderation-setup-instructions). To future proof this I'm putting it into the base template, so that it gets included on all pages on the site.
I haven't got a good way of testing whether this actually makes the moderation tool work other than putting it live and checking, but suggestions welcome!
Part of https://github.com/mysociety/pombola/issues/2281
> Output fb:app_id meta tag on all pages

- pombola/templates/default_base.html
Some templates, such as [blog posts](https://github.com/mysociety/pombola/blob/4d05dc88f3be6acfddc49b18cf4ccff907720557/pombola/south_africa/templates/info/blog_post.html#L17) and [person pages](https://github.com/mysociety/pombola/blob/4d05dc88f3be6acfddc49b18cf4ccff907720557/pombola/core/templates/core/person_base.html#L17), override the `open_graph` template block, which means the `fb:app_id` meta tag isn't in the HTML for those pages.
To avoid that problem this moves the `fb:app_id` meta tag outside any template blocks so that it always appears in the HTML output.
This is the fix I proposed in https://github.com/mysociety/pombola/issues/2281#issuecomment-311941902.
Part of https://github.com/mysociety/pombola/issues/2281
> Always output fb:app_id meta tag

- pombola/core/static/sass/_listing.scss
- pombola/core/templates/core/_position_session_links.html
- pombola/south_africa/migrations/0002_add_parliamentary_sessions.py
For Kenya, we've created instances of a `ParliamentarySession` model to represent a term of a particular house of parliament. (The name is a bit misleading - [it should probably be `Term` instead](https://github.com/mysociety/pombola/issues/2179).) This was introduced primarily so that we could distinguish places from different terms with different boundaries. Later we added links to views of positions of a particular parliament, like:
The position view, when provided with a `session` query parameter, only includes positions whose start and end date overlap with the start and end date of the corresponding `ParliamentarySession`.
In Pombola, this mechanism provides the only easy way to see all the people who were ever a representative in a particular house for a given session, which means …
> ZA: add parliamentary session data for the 25th and 26th parliaments

- .travis.yml
This modifies Pombola's Travis config to include [sending coverage data to Scrutinizer](https://scrutinizer-ci.com/docs/tools/external-code-coverage/) as well as Coveralls.
Scrutinizer will now also [fail a build](https://scrutinizer-ci.com/docs/configuration/build_status) if coverage drops by more than 1%. See [Scrutinizer Config](https://scrutinizer-ci.com/g/mysociety/pombola/settings/build-config) to fine-tune this.
> Add test coverage to Scrutinizer

- pombola/south_africa/static/sass/_south-africa_overrides.scss
Fixes #2268.
Example:
```html
<div class="cta-box">
<p>Things are important</p>
<h2>You should do this thing</h2>
<p>
<a href="#" class="button">Do the thing</a>
</p>
</div>
```
Looks like:
A few generic styles mean you can combine paragraphs, headings, and other block elements in whatever order you like and it should still look fairly good.
> [ZA] Reusable .cta-box component for static pages

- .travis.yml
- pombola/core/static/js/feeds.js
The Google Feed API, which we used to fetch an RSS feed in Javascript
and display it on the homepage, was deprecated and stopped working at
the end of 2016.
There are similar generic services we could use, but it's not clear how
stable or trustworthy those would be, and it's almost as simple to
write our own Javascript for fetching the feed, parsing it and
rendering it as a list, as this commit does.
For this to work there need to be appropriate CORS headers returned by
the server returning the RSS feed. For example, in the case of
Mzalendo, this means that we've added:
Access-Control-Allow-Origin: http://info.mzalendo.com
... to reponses from http://www.mzalendo.com/blog/
Fixes #2292
> The Google Feed API is deprecated and no longer works; replace its use

- pombola/search/tests/fuzzy.py
- pombola/search/views.py
Haystack prevents us from easily applying a [fuzziness to the whole search](https://www.elastic.co/guide/en/elasticsearch/reference/0.90/query-dsl-fuzzy-query.html),
so this is a workaround which checks to see if a string is entirely
alphanumeric ASCII characters and spaces, then applies the fuzzy query
string operator to individual words if so. If not, `AutoQuery()` handles
escaping special characters and turning boolean patterns such as `AND` into
actual structured query objects.
For future reference, this workaround is necessary without radically re-working search throughout Pombola to use less Haystack magic and allow us to modify search kwargs as [suggested on Stack Overflow](https://stackoverflow.com/questions/18000714/how-can-i-do-a-fuzzy-search-using-django-haystack-and-the-elastic …
> [ZA] Add fuzzy search operator to searches.

- pombola/kenya/management/commands/kenya_import_2017_photos.py
This script uses the YNR IDs that the kenya_import_2017_election_results
command added to import the photos from YNR and add them to the
appropriate person in Mzalendo. If there were existing photos of the
person, the YNR photo is not set as primary, otherwise it would be.
> Add a script to import elected candidates' photos from YNR

- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/core/person_detail.html
- pombola/south_africa/tests.py
- pombola/south_africa/views/person.py
Person attendance page:
Changed MINISTER to read MINISTRY, and added some notes on the attendance methodology.
@mhl
> Person attendance: Change wording & clarify methodology

- conf/general.yml-example
- pombola/search/geocoder.py
- pombola/settings/base.py
We have been getting lots of:
GeocoderError: Error OVER_QUERY_LIMIT
... errors from pombola/search/geocoder.py, which we should deal with by
paying for usage of the API. This requires using an an API key to
identify us, hence this change.
Part of the fix for #2313
> Use a Google Maps Geocoding API key if supplied in general.yml

- pombola/south_africa/static/js/tabs.js
While working on #2329, I noticed that the selected tab on a person page wasn’t persisted across page refreshes, despite the tab ID being in the URL hash fragment.
This fixes that, and lets you, for example, share a link directly to a Representative’s "Positions", or "Appearances" … or (once #2329 is merged) "Messages".
> [ZA] Select correct person page tab on pageload

- .travis.yml
This is needed so that psycopg2's version detection works correctly. Without this is uses the default pg_config, which is for 10.2 (at time of writing) which trips up psycopg2's version detection.
https://docs.travis-ci.com/user/database-setup/#Using-pg_config
> Add postgresql-server-dev-9.6 to Travis CI apt packages

- pombola/south_africa/management/commands/south_africa_sync_everypolitician_uuid.py
- requirements.txt
Add a management command add EveryPolitician UUIDs to the Person model.
~~This is currently using the `south-africa-update-peoples-assembly` branch of everypolitician-data, which has the required UUIDs but is also losing some data, so can't be merged in its current state. So before this can be merged we need to fix the problems described in https://github.com/everypolitician/everypolitician-data/issues/42096.~~
To work around this problem I've made the git ref that we use to fetch `countries.json` configurable. This means we can point to the branch that has the data we need for now, then when things are fixed upstream we can use a different ref to point to the fixed data.
I've also split the bit that adds a cronjob for this into a separate pull request …
> Sync EveryPolitician UUID to Person model

- pombola/core/models.py
- pombola/core/tests/test_models.py
Adds a method that returns the EveryPolitician UUID from the persons identifiers if there's one present.
This is needed for the WriteInPublic integration we're doing for South Africa. We're going to need to use the EP UUID quite a bit for that, so I think it makes sense to add a shortcut for accessing that information.
This was extracted from https://github.com/mysociety/pombola/pull/2329 and follows on from #2331.
> Add Person.everypolitician_uuid method

- pombola/writeinpublic/client.py
- pombola/writeinpublic/tests.py
- requirements.txt
This is a very simple wrapper around the WriteInPublic API. Currently it only implements the features that we need for integrating it into Pombola.
I've added some tests for the basic functionality, but in the interests of time I've skipped writing tests for the `.people()` and `.answers()` methods, so will need to revisit that at some point in the future.
Extracted from #2329 
Part of #1682
> Add WriteInPublic API client

- pombola/south_africa/urls.py
This adds the `urls.py` entry to enable the WriteInPublic integration.
Follows on from #2346 
Extracted from #2329 
Part of #2326 
Before merging
> [ZA] Activate WriteInPublic integration

- pombola/south_africa/views/home.py
There is already a "can be featured on homepage" checkbox on people's profiles in the admin. This commit uses that feature to display featured MPs on the homepage. If there is more than one featured MP then an MP will be chosen at random.
Fixes #2354
> [ZA] Use can_be_featured flag for homepage featured MP

- pombola/south_africa/templates/home.html
We received the following request from PMG:
> Just above the featured MP on the homepage, the “Show more MPs” link should link to ‘MP Profiles’ https://www.pa.org.za/position/member/parliament/?order=name&a=1 rather than MP Corner blogs
This pull request changes that link to go to that page.
> [ZA] Change featured MP show more link

- conf/crontab.ugly
Extracted from https://github.com/mysociety/pombola/pull/2331
This adds a cron job that runs the `core_sync_everypolitician_uuid` management command that was added in #2331 once a day on staging and production.
> [South Africa] Add cron job to sync EP UUIDs

- pombola/writeinpublic/migrations/0001_initial.py
- pombola/writeinpublic/models.py
This will contain the configuration to connect to a WriteInPublic instance. This will allow us to connect to multiple WriteInPublic instances, rather than just having one set of configuration values in `general.yml`.
First part of https://github.com/mysociety/pombola/issues/2365
> Add WriteInPublic Configuration model

- pombola/south_africa/urls.py
- pombola/writeinpublic/tests.py
- pombola/writeinpublic/views.py
Following on from #2367 this changes the view to get the configuration from the database, rather than the config file.
Follows on from #2367 
Second part of https://github.com/mysociety/pombola/issues/2365
Please do the following before merging
> Update WriteInPublic views to use configuration values

- pombola/writeinpublic/templates/writeinpublic/pending.html
- pombola/writeinpublic/tests.py
- pombola/writeinpublic/urls.py
- pombola/writeinpublic/views.py
We've enabled moderation on the WriteInPublic instance, which means that the message isn't available via the API immediately. Rather than redirecting to a message page instead we redirect to a pending message page which lets the user know that their message needs to be approved.
This isn't the prettiest page at the moment, but it will at least stop the immediate errors.
Fixes https://github.com/mysociety/pombola/issues/2378
> WriteInPublic: Redirect to pending message page at end of wizard

- pombola/south_africa/tests.py
- pombola/south_africa/urls.py
- pombola/south_africa/views/__init__.py
- pombola/south_africa/views/api.py
This adds an API endpoint which serves up Popolo JSON suitable for feeding into WriteInPublic. This means that any changes to committee email addresses will automatically be reflected in WiP when the datasource is synced.
Currently there aren't any committees with an email address in the production pa.org.za deploy. I added email addresses to a couple of committees locally to test this. Below is an example of the JSON that this call produces, note that the empty `contact_details` array is needed for WriteInPublic, otherwise an error is produced on import.
```json
{
"persons": [
{
"email": "test@example.com",
"contact_details": [],
"id": 1410,
"name": "Ad Hoc Committee on Funding of Political Parties"
},
{
"email": "committee@example.org",
"contact_details": [],
"id": 141,
"name": "Ad Hoc …
```
> [ZA] Add API endpoint to serve committee Popolo JSON

- pombola/south_africa/templates/core/person_detail.html
- pombola/south_africa/templates/home.html
- pombola/south_africa/urls.py
- pombola/writeinpublic/templates/writeinpublic/message.html
- pombola/writeinpublic/templates/writeinpublic/messages.html
- pombola/writeinpublic/templates/writeinpublic/pending.html
- pombola/writeinpublic/templates/writeinpublic/person-write-draft.html
- pombola/writeinpublic/templates/writeinpublic/person-write-preview.html
- pombola/writeinpublic/tests.py
- pombola/writeinpublic/urls.py
- pombola/writeinpublic/views.py
Namespacing the URLs allows us to "mount" multiple instances of the writeinpublic app in the URL config. This means we can have one instance for writing to MPs and another for writing to committees.
This adds namespacing support to the `writeinpublic` app without changing the way it works. This change doesn't add support for committees, that will be added in a separate pull request.
Part of https://github.com/mysociety/pombola/issues/2351
> [WriteInPublic] Use URL namespaces to allow multiple app instances

- pombola/search/views.py
- pombola/south_africa/tests.py
Don't error on a ZERO_RESULTS exception from Google's geocoder
We're getting quite a lot of email errors on PA for people
searching for places which cause pygeocoder to return a
ZERO_RESULTS exception. Here's an example error:
Internal Server Error: /search/location/
Traceback (most recent call last):
File "[...]/pombola-virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "[...]/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
return self.dispatch(request, *args, **kwargs)
File "[...]/pombola-virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
return handler(request, *args, **kwargs) …
> Don't error on a ZERO_RESULTS exception from Google's geocoder

- pombola/writeinpublic/client.py
- pombola/writeinpublic/forms.py
- pombola/writeinpublic/templates/writeinpublic/message.html
- pombola/writeinpublic/tests.py
- pombola/writeinpublic/views.py
Rather than hardcoding the `Person` class all over the place this instead uses an adapter approach, which means we can pass in different adapters to the view which can use different models to get the required information.
This will allow us to have two different WriteInPublic instances, one that uses `Person` models to write to people and another, which is yet to be added, which will allow you to write to a committee, which is represented by the `Organisation` model.
Part of https://github.com/mysociety/pombola/issues/2328
> [WriteInPublic] Make view more generic

- pombola/south_africa/views/person.py
This helps the (rather fragile) link between PMG and PA work when PMG uses https URLs, rather than http.
This is currently preventing PA from showing attendance of many new MPs that have been linked in PMG using 'https' and not 'http'.
> Fix for https PA <-> PMG link

- pombola/south_africa/tests.py
Changing the attendance API to use https broke the tests. This changes the tests to use https to fix things again.
Fixes https://github.com/mysociety/pombola/issues/2397
> Fix South Africa tests

- pombola/writeinpublic/tests.py
- pombola/writeinpublic/views.py
The person adapter's `get` method was referencing a variable that didn't exist. I've fixed it to use the correct variable name and added a regression test.
Fixes https://github.com/mysociety/pombola/issues/2391
> [WriteInPublic] Fix PersonAdapter NameError

- pombola/core/management/commands/core_database_dump.py
This came up in an error email as an unexpected table (it was created by
a recent migration) so no database dump was created. This table contains
sensitive data, so this commit adds it to the tables_to_ignore list.
> Don't include writeinpublic_configuration in public DB dumps

- pombola/writeinpublic/tests.py
- pombola/writeinpublic/views.py
When a committee has multiple email addresses it was being returned as multiple rows from the form's queryset. By adding a `.distinct()` call to that we ensure we're only getting back one row per committee.
Fixes #2402
> [WriteInPublic] Fix error when committee has multiple emails

- pombola/south_africa/templates/core/organisation_detail.html
- pombola/south_africa/tests.py
- pombola/south_africa/views/organisations.py
- pombola/writeinpublic/client.py
- pombola/writeinpublic/tests.py
If the committee that we're requesting message for doesn't exist in the WiP instance then it will return a 404. We want to ignore this error and just use an empty list of messages in the context in that case.
Fixes #2399
> [WriteInPublic] Handle errors when retrieving messages

- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/menu_entries.html
- pombola/south_africa/templates/south_africa/committee_list.html
- pombola/south_africa/urls.py
- pombola/south_africa/views/__init__.py
- pombola/south_africa/views/committees.py
This page lists all NA committees that can be written to, along with a link to the page showing messages sent to a specific committee.
This page is being added in response to feedback from PMG:
> Currently PA does not have a ‘home’ for Committees where the messages can be viewed. Is it possible to create a link to these committees?
It would be good to talk to them about what exactly they want from this page, as at the moment it's quite bare.
Fixes https://github.com/mysociety/pombola/issues/2394
Fixes https://github.com/mysociety/pombola/issues/2328
> [ZA] Add page with a list of NA committees

- pombola/south_africa/static/js/person-messages-ajax.js
When the messages section of a person page was linked to directly the messages weren't loading because the `tabsbeforeactivate` event wasn't being triggered.
To workaround this problem we're now just loading the messages on page load, rather than waiting for the tab to be activated.
Fixes #2353
> [ZA] Always load messages on person profile page

- pombola/core/static/sass/_core.scss
- pombola/south_africa/static/sass/_south-africa_overrides.scss
Fixes #2393.
Fits the two red buttons onto the same line as the heading, on wide screens, without reducing the font-size of the heading, or any of the dimensions of the buttons.
Buttons still break onto a new line, below the heading, on screens narrower than 960px.
While I was there, I also fixed a funky usage of `@extend` that was generating super bloated CSS selectors wherever a `.button` was referenced.
> [ZA] Fit homepage actions onto a single line, on wide screens

- pombola/core/static/sass/_common.scss
- pombola/core/static/sass/admin.scss
- pombola/core/templates/core/position_detail_grid.html
- pombola/kenya/static/js/lazy-loaded-images.js
- pombola/kenya/templates/menu_entries.html
- pombola/settings/kenya_base.py
Fixes #2423.
Sorry, I don‘t have any representative’s photos on my local machine, so there are lots of anonymous placeholder images in the screenshots below. Obviously, on the live site, those images will be replaced by people’s faces :-)
The images now lazy-load, meaning the page should be _fairly_ fast to load the first time, and members’ images will only be pulled in as the user scrolls down.
> Grid layout for Keyna reps

- pombola/south_africa/templates/south_africa/latlon_local_view.html
- pombola/south_africa/views/geolocalization.py
@mhl 
This requests extra info from the mapit API, and adds a link to the ward's local municipality on Municipal Money to the Rep Locator results page.
It seems there aren't any tests for this section of code. Can you please confirm that is the case?
> Add link to MuniMoney on Rep results page

- pombola/south_africa/static/sass/_person-write.scss
- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/writeinpublic/templates/writeinpublic/committee-write-recipients.html
- pombola/writeinpublic/templates/writeinpublic/person-write-recipients.html
**Not ready for review yet**
Fixes #2407.
This currently reuses the national assembly image from https://www.pa.org.za/organisation/national-assembly/ on both WriteInPublic pages. We need to check whether PMG had different images in mind.
> WIP: Add blurb and header images to WriteInPublic pages

- pombola/kenya/templates/menu_entries.html
Fixes #2447.
This includes a new link to `/info/collaboration-outputs` – we’ll need to create that page via the Django admin backend, and let Jessica know so she can start filling it with content.
> [KE] Update nav menu items

- pombola/core/migrations/0008_sort_organisations_by_name.py
- pombola/core/models.py
Changes the default sort order of committees to be alphabetical by `name` instead of `slug`.
* Closes #2406
> Change ordering of committees to alphabetical.

- pombola/core/migrations/0009_organisation_short_name.py
- pombola/core/migrations/0010_organisation_update_short_name.py
- pombola/core/migrations/0011_organisation_alter_short_name.py
- pombola/core/models.py
- pombola/south_africa/templates/south_africa/committee_list.html
- pombola/south_africa/views/api.py
- pombola/south_africa/views/committees.py
- pombola/writeinpublic/forms.py
- pombola/writeinpublic/views.py
As per #2429, shortens the displayed committee names in the contexts of writing to committees via Write in Public.
Closes #2429
> Shorten displayed committee names in some contexts

- conf/crontab.ugly
This adds a new entry to the crontab to run the management command to pull in new SMS messages hourly.
Part of #2462
> [KE] Add cron task to pull in new SMS hourly

- pombola/sms/admin.py
- pombola/sms/migrations/0002_auto_20181003_1515.py
- pombola/sms/models.py
This adds a new model which will contain the SMS question that will be displayed on the homepage.
At the moment this is just a very simple model with a `text` field for storing the question text. We might want to add a published flag or have some more advanced controls in the future, but I think for now we can just pull the most recently created question and display it on the homepage.
Part of #2462
> [Kenya] Add question model for this week's SMS question

- pombola/core/management/commands/core_database_dump.py
Adds the new SMS tables to the list of tables to ignore when doing a DB dump.
Fixes https://github.com/mysociety/pombola/issues/2488
> [KE] Exclude SMS tables from db dump

- pombola/core/templatetags/active_class.py
- pombola/core/tests/test_templatetags.py
- pombola/south_africa/templates/core/place_detail.html
- pombola/south_africa/templates/south_africa/_place_tabs.html
- pombola/south_africa/tests.py
It turns out combining the [/place/&lt;name&gt;](https://www.pa.org.za/place/eastern-cape/) and [/place/&lt;name&gt;/places](https://www.pa.org.za/place/eastern-cape/places/) views was trickier than anticipated.
So while I wait for @chrismytton to find some time for that, here’s a super quick fix for the broken tab styling and extraneous membership total that the PMG folks wanted fixed as part of #2475.
> [ZA] Quick fixes for Province page tab styling

- pombola/hansard/admin.py
Turns out the error was because the template that was supposed to be rendered when there are no more unassigned aliases didn't exist, and from what I can tell never has existed.
To fix this I've switched to showing a flash message when there are no more aliases to assign.
Fixes #2501
> [KE] Fix error clicking Next unassigned entry button in Hansard admin

- pombola/settings/south_africa_base.py
- pombola/surveys/admin.py
- pombola/surveys/migrations/0001_initial.py
- pombola/surveys/models.py
This adds an admin section where you can create and update surveys to be displayed on the homepage. This is the first part, which just adds the model and the admin bits for it. I'm going to do the actual update of the homepage as a separate change, because I need to go and create a survey in the admin first, so there's something to display on the homepage when that's deployed.
Part of https://github.com/mysociety/pombola/issues/2348
> [ZA] Admin section for creating and updating homepage surveys

- pombola/core/management/commands/core_database_dump.py
Should fix this message from cron:
```
The following tables were found which weren't expected
and which hadn't been explicitly excluded.  If these are safe to make
available in a public database dump (in particular check that they
contain no personal information of site users) then add them to
'expected_table'. Otherwise (i.e. they should *not* be made available
publicly) add them to 'tables_to_ignore'.
surveys_survey
```
> [ZA] Add surveys_survey to list of tables to dump

- pombola/south_africa/templates/core/place_detail.html
As requested by PMG, change the accordion links text on the province page.
Fixes #2527 
Part of https://github.com/mysociety/pombola/issues/2475
> [ZA] Change the membership text on province page

- pombola/core/admin.py
- pombola/core/models.py
This adds the relevant bits to the Place model so that it can have images associated with it. It works in the same way as images for people and organisations, you can add images in the admin and then access them in the template with `.primary_image()`.
It seems that the template for the places list already handles displaying images for places, including generating an appropriately sized thumbnail.
Fixes #2496
> Allow places to have images associated with them

- pombola/hansard/models/entry.py
If a person isn't found using the normal lookup methods then try to look
them up using the new "Constituency, Party initials" format.
At the moment this only uses the constituency, since we know which house
the sitting is for and when it took place, so we can get the correct
constituency back from that, and since they're single member
constituencies they should just have one member associated with them.
In it's current state this still has a few issues, such as not handling
more than one place being returned, and it doesn't pay any attention to
the party initials, but from my testing it seems to pick up most of the
basic cases correctly.
Fixes #2473
> [KE] Lookup Hansard speakers by constituency

- pombola/hansard/models/entry.py
The speaker_title is ambiguous for Nominated reps, because some parties have multiple nominated people. So detect these people and fallback to looking up by name using the speaker_title field.
Part of #2473
> [KE] Hansard: Detect nominated reps and lookup by name

- pombola/hansard/models/entry.py
This adds a few enhancements to the Hansard place/party name matching.
- Extract a couple of methods to make logic slightly easier to follow
- Ignore names with month names in
- Change party initials regex to require 2+ capital letters
- Create aliases for anything that we think matches the correct format, but can't be matched in the DB.
Part of https://github.com/mysociety/pombola/issues/2473
> [KE] Various hansard name matching fixes and enhancements

- pombola/core/templatetags/clean_html.py
- pombola/core/tests/test_clean_html_templatetags.py
We were seeing errors when trying to clean a document that only contained three closing HTML tags. This fix refactors the `as_clean_html` template tag to handle any lxml errors and return an empty paragraph element.
Fixes #2574
> Handle all types of lxml error in as_clean_html

- pombola/south_africa/templates/south_africa/latlon_local_view.html
The Ward Councillor tab is the default view when you search for an address, but for some reason the MPs tab was also being marked as active, which meant that two tabs were receiving the active class when the rep locator loaded.
This change removes the HTML class for active tabs and leaves it to the JS to control it.
Fixes https://github.com/mysociety/pombola/issues/2555
> [ZA] Fix multiple active tabs on rep locator

- pombola/south_africa/templatetags/za_people_display.py
This template tag was being called without an organisation, so in production it was just silently failing, but in development it was raising an exception.
This adds an extra check so that if there is no organisation then we just short circuit and return `True`.
Fixes https://github.com/mysociety/pombola/issues/2528
Part of https://github.com/mysociety/pombola/issues/2475
> [ZA] Fix display of people on constituency office page

- pombola/core/migrations/0012_organisation_seats.py
- pombola/core/models.py
- pombola/core/templates/core/organisation_list_item.html
- pombola/core/views.py
- pombola/search/templates/search/items/organisation.html
- pombola/south_africa/templates/core/organisation_list_item.html
- pombola/south_africa/templates/core/parliament_list_item.html
- pombola/surveys/migrations/0002_auto_20190319_1101.py
Adds a new `seats` field to `Organisation`s, representing the nominal number of seats. Displays this instead of the number of position holders (which has renamed variables elsewhere for clarity).
Closes #2556 
---
> [ZA] Set number of members in the assembly and NCOP to be static

- .travis.yml
- pombola/writeinpublic/client.py
- pombola/writeinpublic/views.py
Previously an HTTPError was being raised, which was causing the view to
return a 500 error when a message couldn't be found. This change means
we correctly return a 404 error when a message isn't found.
Fixes #2589
> [ZA] WriteInPublic: Return a 404 error when a message can't be found

- requirements.txt
Newer versions depend on a newer version of pytz. So rather than face
that potential dependency hell let's just pin to the version that we
know works.
This should fix the Travis build.
> Pin babel dependency at 2.6.0

- .travis.yml
Given that Scrutinizer appears to no longer be returning actual useful analysis of any of the code, and just serves to report on coverage, this PR swaps to CodeClimate (which does useful static analysis _and_ useful reporting of code coverage).
> Swap Scrutinizer for CodeClimate

- pombola/core/admin.py
Adds the `ParliamentarySession` model to the admin interface, so that the 27th Parliament sessions can be added.
> Add admin for Parliamentary Sessions

- pombola/south_africa/templates/menu_entries.html
PMG have requested that this link be removed as the [/person/all/](https://www.pa.org.za/person/all/) page isn't terribly useful.
> [ZA] Don't link to /person/all/ from menu bar

- Vagrantfile
Trying to install multiple Vagrant boxes for different countries results in:
```
A VirtualBox machine with the name 'vagrant-pombola' already exists.
Please use another name or delete the machine with the existing
name, and try again.
```
This PR avoids this collision by adding the country name to the Vagrant box name.
> Support multiple Vagrant boxes for different countries

- .gitignore
We're temporarily using a version of Ruby from rbenv on the mySociety servers until we upgrade to stretch, so ignore the generated `.ruby-version` file.
Related to https://github.com/mysociety/pombola/issues/2596
> Ignore .ruby-version file

- conf/crontab.ugly
This should prevent the cron errors saying `/bin/sh: 1: output-on-error: not found`.
Fixes https://github.com/mysociety/pombola/issues/2618
> Add commonlib to crontab path

- pombola/south_africa/views/elections.py
This means we can avoid a 500 error if a province doesn't exist.
Fixes https://github.com/mysociety/pombola/issues/1900
> Use get_object_or_404 in election province view

- pombola/core/management/commands/core_merge_people.py
- pombola/core/management/merge.py
- pombola/core/tests/test_commands.py
Without this check you can accidentally merge someone that's hidden into someone who isn't and they'll also end up hidden.
Fixes https://github.com/mysociety/pombola/issues/2425
> Check for mismatch in hidden field when merging people

- pombola/settings/base.py
- pombola/whitenoise_pipeline.py
- requirements.txt
This was added as part of the Heroku support which has now been removed. It seems that this was actually always incorrectly configured, as I think this storage was only supposed to be used on Heroku, but was configured to work everywhere but Heroku.
Part of https://github.com/mysociety/pombola/issues/2603
> Remove whitenoise

- bin/prepare_environment.bash
This effectively just runs the migrations, which means we're running migrations twice on each deploy. Also the syncdb command is being removed in an upcoming version of Django, so we'd need to remove it then anyway.
> Remove ./manage.py syncdb from bin/prepare_environment.bash

- requirements.txt
This doesn't seem to be used anywhere, so it can be removed from requirements.txt.
> Remove pymongo dependency

- .travis.yml
- requirements.txt
Update django-sayit and related dependencies. I've had to use haystack 2.6.1 to avoid test failures, but this conflicts with django-sayit's version, so I've had to disable the `pip check` step in `.travis.yml` for now.
Part of #2585
> Upgrade django-sayit

- docs/BACKGROUND.md
- docs/INSTALL.md
Update `INSTALL.md` markdown flavour to be consistent with other markdown files and move the Vagrant documentation from `BACKGROUND.md` to `INSTALL.md`.
Related to https://github.com/mysociety/pombola/issues/2635
> Update install documentation

- bin/vagrant-install.bash
- pombola/core/management/commands/core_database_dump.py
Newer installations may include PostGIS extensions that cause permissions issues when dumping the schema as a non-superuser. This limits the schema dump to the public schema.
When creating a database to restore into, the `postgis` and `postgis_topology` extensions will need to be activated during provisioning.
> Only include the public schema in the database dumps

- pombola/south_africa/static/js/attendance-table.js
- pombola/south_africa/templates/south_africa/mp_attendance.html
- pombola/south_africa/tests.py
- pombola/south_africa/views/attendance.py
This adds a position column to the table when viewing attendance for ministers in order to differentiate between ministers and deputies.
When we retrieve the ministerial positions, we sort by person, then by start date, in order to group by person, and have their latest position last when iterating over the list and setting their position in the attendance records.
> Add position column to minister attendance table

- pombola/south_africa/tests.py
- pombola/south_africa/views/attendance.py
This is a bit ugly, but we need to differentiate 2019 attendance between pre- and post-election records, the dividing date being the opening of the 6th parliament, 1 July 2019.
The PMG API returns annual data from 1 Jan - 31 Dec, so if the user has selected to view records for 2019 (which is the default view for the page until there we receive records for 2020), we divide the results into those before and after 1 July 2019 return the selected records.
> 2646 pre and post 2019 election attendance

- pombola/south_africa/data/elections/2019/committee-emails.csv
- pombola/south_africa/data/elections/2019/na-emails.csv
- pombola/south_africa/management/commands/south_africa_import_email_addresses_elections_2019.py
This adds the CSVs containing new email addresses for MPs and committees after the 2019 elections. It also contains a management command for importing the National Assembly emails into the database. I haven't added a similar command for the committees yet, I'll do that in a separate pull request.
Part of https://github.com/mysociety/pombola/issues/2593
> Import new National Assembly emails post 2019 elections

- pombola/core/admin.py
- pombola/core/migrations/0013_organisation_show_attendance.py
- pombola/core/models.py
- pombola/south_africa/admin.py
- pombola/south_africa/models.py
- pombola/south_africa/tests.py
- pombola/south_africa/views/person.py
This allows the admin users of the ZA instance to toggle displaying attendance records on the person detail pages for people belonging to a specific party.
The migration sets the field to True fro the three major parties which they would like to have display the records.
The admin page excludes the field in `core`, and allows a ZA user to toggle the field in a different section based on a proxy of the `Organization` model. Only parties are shown on the list page, and users can only edit the objects - not add or delete.
An example of a person detail page affected by this change is:
https://www.pa.org.za/person/liezl-linda-van-der-merwe/
> Admin attendance toggle for ZA parties

- pombola/south_africa/static/js/interests-filter.js
- pombola/south_africa/static/sass/_south-africa_overrides.scss
- pombola/south_africa/templates/interests_register/index.html
- pombola/south_africa/views/interests.py
A few improvements to improve user interaction with the filters on the MP assets list page.
https://www.pa.org.za/interests/
Different ways to group the data was separated from the filters to make that fact more obvious.
e.g. Number of declarations per MP. A user now selects the way tp group the results first, and then filters those results.
Only the appropriate categories are returned when viewing the numbers by source.
> Improve MP assets filter interaction

- requirements.txt
When we upgraded Pillow before we started seeing errors like the
following:
IOError: cannot write mode RGBA as JPEG
As a quick workaround we just downgraded Pillow, but that created a
different error:
IOError: encoder error -2 when writing image file
I've dug into this a bit more and it seems that the first error is fixed
in sorl-thumbnail 12.4.1. I think I tried upgrading to the latest sorl,
but that isn't compatible with Django 1.8, which is the version we're
currently on. So this change upgrades to the latest version of Pillow,
and to the latest compatible version of sorl.
Fixes https://github.com/mysociety/pombola/issues/2649
Fixes https://github.com/mysociety/pombola/issues/2669
> Upgrade sorl-thumbnail and Pillow

- pombola/core/management/commands/core_database_dump.py
Without this change there's the possibility of database credentials leaking out.
> Handle SSH errors in core_database_dump command

- pombola/south_africa/tests.py
- pombola/south_africa/views/attendance.py
@chrismytton 
Some previous ministers are no longer members of parties. We need to check for this before trying to access an element in the parties list.
We also only display these ministers when the page is not filtered by party.
> Only display ministers without a party, when not filtered by party

- pombola/hansard/kenya_parser.py
This doesn't seem to cause any problems that I can see in the parsing. Closes #2680
> Update version requirement for pdftohtml
